/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.siuden.analyzer.view;

import ar.com.siuden.analyzer.controller.ClarinController;
import ar.com.siuden.analyzer.controller.GacetaController;
import ar.com.siuden.analyzer.controller.NacionController;
import java.util.Calendar;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author juliozilman
 */
@Component
public class ContadorDePalabras extends javax.swing.JFrame {

    @Autowired
    private GacetaController gacetaController;
    @Autowired
    private NacionController nacionController;
    @Autowired
    private ClarinController clarinController;
    @Autowired
    private PeriodoBusqueda periodoBusqueda;
    private List<String> link;
    private boolean esPorPerido;
    @Autowired
    private BarProgress barProgress;
    private String usarProceso;

    /**
     * Creates new form ContadorDePalabras
     */
    public ContadorDePalabras() {
    }

    public void iniciar() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnContadorPalabraGaceta = new javax.swing.JButton();
        btnContadorPalabraNacion = new javax.swing.JButton();
        btnContadorPalabraClarin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnContadorPalabraGaceta.setText("Contador Diario la Gaceta");
        btnContadorPalabraGaceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContadorPalabraGacetaActionPerformed(evt);
            }
        });

        btnContadorPalabraNacion.setText("Contador Diario la Naciòn");
        btnContadorPalabraNacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContadorPalabraNacionActionPerformed(evt);
            }
        });

        btnContadorPalabraClarin.setText("Contador Diario el Clarin");
        btnContadorPalabraClarin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContadorPalabraClarinActionPerformed(evt);
            }
        });

        jLabel1.setText("Aclaración Si presiona cualquier opciones de buscador de palabra el sistema procesara las paginas ");

        jLabel2.setText("buscando las palabras que coincidan en la busqueda, cada 30 noticias que encuentre generará un archivo excel");

        jLabel3.setText("y lo guardara en la carpeta dependiendo la opción /Gaceta  /Nacion  /Clarin ");

        jButton4.setText("Ver contenido");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnContadorPalabraGaceta, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(btnContadorPalabraNacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnContadorPalabraClarin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                    .addComponent(jButton4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnContadorPalabraGaceta, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btnContadorPalabraNacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnContadorPalabraClarin, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContadorPalabraGacetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContadorPalabraGacetaActionPerformed
        usarProceso = "GACETA";
        barProgress.setEsProceso(usarProceso);
        periodoBusqueda.setVisible(true);
    }//GEN-LAST:event_btnContadorPalabraGacetaActionPerformed

    private void btnContadorPalabraNacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContadorPalabraNacionActionPerformed
        // TODO add your handling code here:
        usarProceso = "NACION";
        barProgress.setEsProceso(usarProceso);
        periodoBusqueda.setVisible(true);
    }//GEN-LAST:event_btnContadorPalabraNacionActionPerformed

    /**
     * @return the esPorPerido
     */
    public boolean isEsPorPerido() {
        return esPorPerido;
    }

    /**
     * @param esPorPerido the esPorPerido to set
     */
    public void setEsPorPerido(boolean esPorPerido) {
        this.esPorPerido = esPorPerido;
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        barProgress.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnContadorPalabraClarinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContadorPalabraClarinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContadorPalabraClarinActionPerformed

    public void procesarPeriodo() {
        if (periodoBusqueda.getReturnStatus() == 1) {
            //gacetaController.setCantidadPagina(1);
            //gacetaController.setVisible(true);
            usarProceso = usarProceso.trim();

            if (usarProceso.equals("NACION")) {
                nacionController.setFechaDesde(periodoBusqueda.getFechaDesde());
                nacionController.setFechaHasta(periodoBusqueda.getFechaHasta());
                barProgress.hilo();
                barProgress.setVisible(true);
            }
            if (usarProceso.equals("GACETA")) {
                gacetaController.setFechaDesde(periodoBusqueda.getFechaDesde());
                gacetaController.setFechaHasta(periodoBusqueda.getFechaHasta());
                barProgress.hilo();
                barProgress.setVisible(true);
            }

            if (usarProceso.equals("CLARIN")) {
                clarinController.setFechaDesde(periodoBusqueda.getFechaDesde());
                clarinController.setFechaHasta(periodoBusqueda.getFechaHasta());
                clarinController.calcularCantidadDia(periodoBusqueda.getFechaDesde(),periodoBusqueda.getFechaHasta());
                barProgress.hilo();
                barProgress.setVisible(true);
            }
        }
    }

    public GacetaController getGacetaController() {
        return gacetaController;
    }

    public NacionController getNacionController() {
        return nacionController;
    }

    public ClarinController getClarinController() {
        return clarinController;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContadorDePalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContadorDePalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContadorDePalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContadorDePalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContadorDePalabras().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContadorPalabraClarin;
    private javax.swing.JButton btnContadorPalabraGaceta;
    private javax.swing.JButton btnContadorPalabraNacion;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
